# Generated by Django 2.0.1 on 2019-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190521_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstype',
            name='name',
        ),
        migrations.AlterField(
            model_name='accesstype',
            name='code',
            field=models.PositiveIntegerField(choices=[(1, 'MAINTAINER'), (2, 'DEVELOPER'), (3, 'REPORTER'), (4, 'GUEST'), (5, 'OTHERS')], default=5),
        ),
    ]
