# Generated by Django 2.0.1 on 2019-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190521_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_type',
            field=models.PositiveIntegerField(choices=[(0, 'OWNER'), (1, 'MAINTAINER'), (2, 'DEVELOPER'), (3, 'REPORTER'), (4, 'GUEST'), (5, 'OTHERS')], default=5),
        ),
    ]
