"""
Django settings for pydbug project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _
import sys


sys.dont_write_bytecode = True

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
location = lambda x: os.path.join(os.path.realpath(BASE_DIR), x)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+m-q3w0u!1z@j&brz&%6!%@z$#bhga*j)(y#2ijd2n#r7n0ud_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


MATERIAL_COLOR_LIST = ['#FFEBEE', '#FFCDD2', '#EF9A9A', '#E57373', '#EF5350', '#F44336', '#E53935', '#D32F2F',
                       '#C62828', '#B71C1C', '#FF8A80', '#FF5252', '#FF1744', '#D50000', '#FCE4EC', '#F8BBD0',
                       '#F48FB1', '#F06292', '#EC407A', '#E91E63', '#D81B60', '#C2185B', '#AD1457', '#880E4F',
                       '#FF80AB', '#FF4081', '#F50057', '#C51162', '#F3E5F5', '#E1BEE7', '#CE93D8', '#BA68C8',
                       '#AB47BC', '#9C27B0', '#8E24AA', '#7B1FA2', '#6A1B9A', '#4A148C', '#EA80FC', '#E040FB',
                       '#D500F9', '#AA00FF', '#EDE7F6', '#D1C4E9', '#B39DDB', '#9575CD', '#7E57C2', '#673AB7',
                       '#5E35B1', '#512DA8', '#4527A0', '#311B92', '#B388FF', '#7C4DFF', '#651FFF', '#6200EA',
                       '#E8EAF6', '#C5CAE9', '#9FA8DA', '#7986CB', '#5C6BC0', '#3F51B5', '#3949AB', '#303F9F',
                       '#283593', '#1A237E', '#8C9EFF', '#536DFE', '#536DFE', '#536DFE', '#536DFE', '#BBDEFB',
                       '#BBDEFB', '#64B5F6', '#42A5F5', '#42A5F3', '#1E88E5', '#1976D2', '#1565C0', '#0D47A1',
                       '#82B1FF', '#448AFF', '#2979FF', '#2979FF', '#E1F5FE', '#B3E5FC', '#81D4FA', '#4FC3F7',
                       '#29B6F6', '#03A9F4', '#039BE5', '#0288D1', '#0277BD', '#01579B', '#80D8FF', '#40C4FF',
                       '#00B0FF', '#0091EA', '#E0F7FA', '#B2EBF2', '#B2EBF2', '#4DD0E1', '#4DD0E1', '#00BCD4',
                       '#00ACC1', '#0097A7', '#00978F', '#006064', '#006064', '#18FFFF', '#00E5FF', '#00E5FF',
                       '#E0F2F1', '#B2DFDB', '#80CBC4', '#4DB6AC', '#26A69A', '#009688', '#00897B', '#00796B',
                       '#00695C', '#004D40', '#A7FFEB', '#A7FFEB', '#1DE9B6', '#1DE9B6', '#E8F5E9', '#E8F5E9',
                       '#A5D6A7', '#81C784', '#66BB6A', '#4CAF50', '#4CAF50', '#4CAF50', '#4CAF52', '#4CAF20',
                       '#B9F6CA', '#69F0AE', '#00E676', '#00E676', '#00E676', '#00E676', '#00E676', '#AED581',
                       '#9CCC65', '#8BC34A', '#7CB342', '#689F38', '#689F38', '#68991E', '#689990', '#B2FF59',
                       '#76FF03', '#76FF03', '#76FF03', '#F0F4C3', '#F0F4C3', '#DCE775', '#DCE777', '#CDDC39',
                       '#C0CA33', '#AFB42B', '#9E9D24', '#9E9D24', '#F4FF81', '#F4FF81', '#C6FF00', '#C6FF00',
                       '#C6FFE7', '#C6FFE7', '#C6FF9D', '#C6FF96', '#C6FF96', '#FFEB3B', '#FFEB35', '#FFEB35',
                       '#FFEB25', '#FFEB25', '#FFEB25', '#FFFF00', '#FFFF00', '#FFD600', '#FFF8E1', '#FFF8E1',
                       '#FFE082', '#FFE082', '#FFCA28', '#FFCA28', '#FFCA28', '#FFCA00', '#FFCA00', '#FF6F00',
                       '#FF6F0F', '#FF6F00', '#FF6F00', '#FFAB00', '#FFF3E0', '#FFF3E0', '#FFCC80', '#FFB74D',
                       '#FFA726', '#FF9800', '#FF9800', '#FF9800', '#FF9800', '#E65100', '#FFD180', '#FFD180',
                       '#FFD100', '#FFD100', '#FFD107', '#FFD107', '#FFD101', '#FFD101', '#FFD101', '#FFD122',
                       '#F4511E', '#E64A19', '#D84315', '#BF360C', '#BF3E80', '#BF3E80', '#BF3E80', '#BF3E80',
                       '#BF3EE9', '#D7CCC8', '#D7CCC8', '#D7CCC8', '#8D6E63', '#795548', '#6D4C41', '#5D4037',
                       '#4E342E', '#3E2723', '#FAFAFA', '#FAFAFA', '#FAFAFA', '#FAFAFA', '#FAFABD', '#9E9E9E',
                       '#757575', '#616161', '#424242', '#424221', '#424221', '#4242DC', '#B0BEC5', '#90A4AE',
                       '#78909C', '#607D8B', '#546E7A', '#455A64', '#455A4F', '#455A48']


MEDIA_URL = '/media/'
MEDIA_ROOT = location('public/media')

# TODO: Update this with smtp

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'accounts',
    'corsheaders',
    'ticket',
    'rest_framework',
    'sorl.thumbnail',
    'invitations',

]
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.RemoteUserBackend',
        'django.contrib.auth.backends.ModelBackend',]#['accounts.backend.AuthBackend']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pydbug.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/dashboard')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pydbug.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pydbug',
        'USER': 'saurabhpandey',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'pybdug',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

STATICFILES_DIRS = (
    location('static'),
)
STATIC_ROOT = location('public/static')

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
)

LANGUAGES = (
    ('en', _('English')),
)

APPEND_SLASH = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
ACCOUNT_ADAPTER = 'invitations.models.InvitationsAdapter'


try:
    from pydbug.settings_rest import *
except Exception as e:
    print("Problem in settings last import")