# Generated by Django 2.0.1 on 2019-05-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_org', to='ticket.Organisation'),
        ),
    ]
