# Generated by Django 2.0.1 on 2019-05-21 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0003_auto_20190521_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('team_name', models.CharField(max_length=256)),
                ('team_description', models.TextField(blank=True, null=True)),
                ('project_id', models.CharField(blank=True, max_length=256, null=True)),
                ('vcs_ip', models.CharField(blank=True, max_length=256, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_team_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_team', to='ticket.Department')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_team_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
