# Generated by Django 2.0.1 on 2019-05-21 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190521_1922'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0004_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleToTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_peopletoteam_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_to_profile', to='accounts.Profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_to_team', to='ticket.Team')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_peopletoteam_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
