# Generated by Django 2.0.1 on 2019-05-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_ticketcomment_ticketfile_ticketfilecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfile',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
