# Generated by Django 2.0.1 on 2019-05-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20190523_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='old_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
    ]
