# Generated by Django 2.0.1 on 2019-05-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20190523_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ticket.Team'),
        ),
    ]
