# Generated by Django 2.0.1 on 2019-05-29 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190521_1922'),
        ('ticket', '0010_ticket_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='team',
            name='project_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='accounts.Profile'),
        ),
    ]
