# Generated by Django 2.0.1 on 2019-05-29 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0011_auto_20190529_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAccessLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('access_type', models.PositiveIntegerField(choices=[(0, 'OWNER'), (1, 'MAINTAINER'), (2, 'DEVELOPER'), (3, 'TESTER'), (4, 'REPORTER'), (5, 'GUEST'), (6, 'OTHERS')], default=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_teamaccesslevel_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('p2t', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_level', to='ticket.PeopleToTeam')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_teamaccesslevel_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
