# Generated by Django 2.0.1 on 2019-06-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20190603_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='team_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_team', to='ticket.Team'),
        ),
    ]
