# Generated by Django 2.0.1 on 2019-06-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_ticket_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='team_name',
        ),
    ]
