# Generated by Django 2.0.1 on 2019-06-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_usergroup_usergrouptopeople'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
