# Generated by Django 2.0.1 on 2019-07-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_peopletoorg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firstquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_one', models.TextField()),
                ('first_two', models.TextField()),
                ('first_three', models.TextField()),
                ('first_four', models.TextField()),
                ('first_five', models.TextField()),
                ('first_six', models.TextField()),
                ('first_seven', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='firstquestion',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Project'),
        ),
    ]
