# Generated by Django 2.0.1 on 2019-07-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_auto_20190725_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestion',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_one', to='ticket.Project'),
        ),
    ]
